spring.application.name=BiomeLab

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//oracle.fiap.com.br:1521/ORCL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME=RM561713}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD=290107}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect